"use strict";
var currencyFormatIso = {
  currencies: {
    "UAE DirhamI (AED)": {
      ISOAlphacode: "AED",
      name: "UAE DirhamI",
      ISONumeric: 784,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: true,
      grapheme: "&#x62f;&#x2e;&#x625;",
      template: "$1 ",
    },
    "Lek (ALL)": {
      ISOAlphacode: "ALL",
      name: "Lek",
      ISONumeric: 8,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: true,
      grapheme: "&#x4c;&#x65;&#x6b;",
      template: "$1 ",
    },
    "Armenian Dram (AMD)": {
      ISOAlphacode: "AMD",
      name: "Armenian Dram",
      ISONumeric: 51,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: false,
      grapheme: "",
      template: "$1 ",
    },
    "Kwanza (AOA)": {
      ISOAlphacode: "AOA",
      name: "Kwanza",
      ISONumeric: 973,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: false,
      grapheme: "",
      template: "$1 ",
    },
    "Argentine Peso (ARS)": {
      ISOAlphacode: "ARS",
      name: "Argentine Peso",
      ISONumeric: 32,
      fractionSize: 2,
      displayFormat: "#.###,##",
      thousandSeparator: ".",
      decimalSeparator: ",",
      hasSymbol: true,
      grapheme: "&#x24;",
      template: "$1 ",
    },
    "Australian Dollar (AUD)": {
      ISOAlphacode: "AUD",
      name: "Australian Dollar",
      ISONumeric: 36,
      fractionSize: 2,
      displayFormat: "# ###.##",
      thousandSeparator: " ",
      decimalSeparator: ".",
      hasSymbol: true,
      grapheme: "&#x24;",
      template: "$1 ",
    },
    "Aruban Forin (AWG)": {
      ISOAlphacode: "AWG",
      name: "Aruban Forin",
      ISONumeric: 533,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: true,
      grapheme: "&#x192;",
      template: "$1 ",
    },
    "Azerbaijanian Manat (AZN)": {
      ISOAlphacode: "AZN",
      name: "Azerbaijanian Manat",
      ISONumeric: 944,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: true,
      grapheme: "&#x43c;&#x430;&#x43d;",
      template: "$1 ",
    },
    "Convertible Mark (BAM)": {
      ISOAlphacode: "BAM",
      name: "Convertible Mark",
      ISONumeric: 977,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: true,
      grapheme: "&#x4b;&#x4d;",
      template: "$1 ",
    },
    "Barbados Dollar (BBD)": {
      ISOAlphacode: "BBD",
      name: "Barbados Dollar",
      ISONumeric: 52,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: true,
      grapheme: "&#x24;",
      template: "$1 ",
    },
    "Taka (BDT)": {
      ISOAlphacode: "BDT",
      name: "Taka",
      ISONumeric: 50,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: false,
      grapheme: "",
      template: "$1 ",
    },
    "Bulgarian Lev (BGN)": {
      ISOAlphacode: "BGN",
      name: "Bulgarian Lev",
      ISONumeric: 975,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: true,
      grapheme: "&#x43b;&#x432;",
      template: "$1 ",
    },
    "Bahraini Dinar (BHD)": {
      ISOAlphacode: "BHD",
      name: "Bahraini Dinar",
      ISONumeric: 48,
      fractionSize: 3,
      displayFormat: "#,###.###",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: false,
      grapheme: "",
      template: "$1 ",
    },
    "Burundi Franc (BIF)": {
      ISOAlphacode: "BIF",
      name: "Burundi Franc",
      ISONumeric: 108,
      fractionSize: 0,
      displayFormat: "#,###",
      thousandSeparator: ",",
      decimalSeparator: "",
      hasSymbol: false,
      grapheme: "",
      template: "$1 ",
    },
    "Bermudian Dollar (BMD)": {
      ISOAlphacode: "BMD",
      name: "Bermudian Dollar",
      ISONumeric: 60,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: true,
      grapheme: "&#x24;",
      template: "$1 ",
    },
    "Brunei Dollar (BND)": {
      ISOAlphacode: "BND",
      name: "Brunei Dollar",
      ISONumeric: 96,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: true,
      grapheme: "&#x24;",
      template: "$1 ",
    },
    "Boliviano (BOB)": {
      ISOAlphacode: "BOB",
      name: "Boliviano",
      ISONumeric: 68,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: true,
      grapheme: "&#x24;&#x62;",
      template: "$1 ",
    },
    "Brazilian Real (BRL)": {
      ISOAlphacode: "BRL",
      name: "Brazilian Real",
      ISONumeric: 986,
      fractionSize: 2,
      displayFormat: "#.###,##",
      thousandSeparator: ".",
      decimalSeparator: ",",
      hasSymbol: true,
      grapheme: "&#x52;&#x24;",
      template: "$1 ",
    },
    "Bahamian Dollar (BSD)": {
      ISOAlphacode: "BSD",
      name: "Bahamian Dollar",
      ISONumeric: 44,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: true,
      grapheme: "&#x24;",
      template: "$1 ",
    },
    "Ngultrum (BTN)": {
      ISOAlphacode: "BTN",
      name: "Ngultrum",
      ISONumeric: 64,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: false,
      grapheme: "",
      template: "$1 ",
    },
    "Pula (BWP)": {
      ISOAlphacode: "BWP",
      name: "Pula",
      ISONumeric: 72,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: true,
      grapheme: "&#x50;",
      template: "$1 ",
    },
    "Belarusian Ruble (BYN)": {
      ISOAlphacode: "BYN",
      name: "Belarusian Ruble",
      ISONumeric: 974,
      fractionSize: 0,
      displayFormat: "#,###",
      thousandSeparator: ",",
      decimalSeparator: "",
      hasSymbol: true,
      grapheme: "&#x42;&#x72;",
      template: "$1 ",
    },
    "Belize Dollar (BZD)": {
      ISOAlphacode: "BZD",
      name: "Belize Dollar",
      ISONumeric: 84,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: true,
      grapheme: "&#x42;&#x5a;&#x24;",
      template: "$1 ",
    },
    "Canadian Dollar (CAD)": {
      ISOAlphacode: "CAD",
      name: "Canadian Dollar",
      ISONumeric: 124,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: true,
      grapheme: "&#x24;",
      template: "$1 ",
    },
    "Congolese Franc (CDF)": {
      ISOAlphacode: "CDF",
      name: "Congolese Franc",
      ISONumeric: 976,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: false,
      grapheme: "",
      template: "$1 ",
    },
    "Swiss Franc (CHF)": {
      ISOAlphacode: "CHF",
      name: "Swiss Franc",
      ISONumeric: 756,
      fractionSize: 2,
      displayFormat: "#'###.##",
      thousandSeparator: "'",
      decimalSeparator: ".",
      hasSymbol: true,
      grapheme: "&#x43;&#x48;&#x46;",
      template: "$1 ",
    },
    "Unidad de Fomento (CLF)": {
      ISOAlphacode: "CLF",
      name: "Unidad de Fomento",
      ISONumeric: 990,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: false,
      grapheme: "",
      template: "$1 ",
    },
    "Chilean Peso (CLP)": {
      ISOAlphacode: "CLP",
      name: "Chilean Peso",
      ISONumeric: 152,
      fractionSize: 0,
      displayFormat: "#.###",
      thousandSeparator: ".",
      decimalSeparator: "",
      hasSymbol: true,
      grapheme: "&#x24;",
      template: "$1 ",
    },
    "Yuan Renminbi (CNY)": {
      ISOAlphacode: "CNY",
      name: "Yuan Renminbi",
      ISONumeric: 156,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: true,
      grapheme: "&#xa5;",
      template: "$1 ",
    },
    "Colombian Peso (COP)": {
      ISOAlphacode: "COP",
      name: "Colombian Peso",
      ISONumeric: 170,
      fractionSize: 2,
      displayFormat: "#.###,##",
      thousandSeparator: ".",
      decimalSeparator: ",",
      hasSymbol: true,
      grapheme: "&#x24;",
      template: "$1 ",
    },
    "Costa Rican Colon (CRC)": {
      ISOAlphacode: "CRC",
      name: "Costa Rican Colon",
      ISONumeric: 188,
      fractionSize: 2,
      displayFormat: "#.###,##",
      thousandSeparator: ".",
      decimalSeparator: ",",
      hasSymbol: true,
      grapheme: "&#x20a1;",
      template: "$1 ",
    },
    "Cabo Verde Escudo (CVE)": {
      ISOAlphacode: "CVE",
      name: "Cabo Verde Escudo",
      ISONumeric: 132,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: false,
      grapheme: "",
      template: "$1 ",
    },
    "Czech Koruna (CZK)": {
      ISOAlphacode: "CZK",
      name: "Czech Koruna",
      ISONumeric: 203,
      fractionSize: 2,
      displayFormat: "#.###,##",
      thousandSeparator: ".",
      decimalSeparator: ",",
      hasSymbol: true,
      grapheme: "&#x4b;&#x10d;",
      template: "1$ ",
    },
    "Djibouti Franc (DJF)": {
      ISOAlphacode: "DJF",
      name: "Djibouti Franc",
      ISONumeric: 262,
      fractionSize: 0,
      displayFormat: "#,###",
      thousandSeparator: ",",
      decimalSeparator: "",
      hasSymbol: false,
      grapheme: "",
      template: "$1 ",
    },
    "Danish Krone (DKK)": {
      ISOAlphacode: "DKK",
      name: "Danish Krone",
      ISONumeric: 208,
      fractionSize: 2,
      displayFormat: "#.###,##",
      thousandSeparator: ".",
      decimalSeparator: ",",
      hasSymbol: true,
      grapheme: "&#x6b;&#x72;",
      template: "$1 ",
    },
    "Dominican Peso (DOP)": {
      ISOAlphacode: "DOP",
      name: "Dominican Peso",
      ISONumeric: 214,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: true,
      grapheme: "&#x52;&#x44;&#x24;",
      template: "$1 ",
    },
    "Algerian Dinar (DZD)": {
      ISOAlphacode: "DZD",
      name: "Algerian Dinar",
      ISONumeric: 12,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: false,
      grapheme: "",
      template: "$1 ",
    },
    "Egyptian Pound (EGP)": {
      ISOAlphacode: "EGP",
      name: "Egyptian Pound",
      ISONumeric: 818,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: true,
      grapheme: "&#xa3;",
      template: "$1 ",
    },
    "Nakfa (ERN)": {
      ISOAlphacode: "ERN",
      name: "Nakfa",
      ISONumeric: 232,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: false,
      grapheme: "",
      template: "$1 ",
    },
    "Ethiopian Birr (ETB)": {
      ISOAlphacode: "ETB",
      name: "Ethiopian Birr",
      ISONumeric: 230,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: false,
      grapheme: "",
      template: "$1 ",
    },
    "Euro (EUR)": {
      ISOAlphacode: "EUR",
      name: "Euro",
      ISONumeric: 978,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: true,
      grapheme: "&#x20ac;",
      template: "$1 ",
    },
    "Fiji Dollar (FJD)": {
      ISOAlphacode: "FJD",
      name: "Fiji Dollar",
      ISONumeric: 242,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: true,
      grapheme: "&#x24;",
      template: "$1 ",
    },
    "Falkland Islands Pound (FKP)": {
      ISOAlphacode: "FKP",
      name: "Falkland Islands Pound",
      ISONumeric: 238,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: true,
      grapheme: "&#xa3;",
      template: "$1 ",
    },
    "Pound Sterling (GBP)": {
      ISOAlphacode: "GBP",
      name: "Pound Sterling",
      ISONumeric: 826,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: true,
      grapheme: "&#xa3;",
      template: "$1 ",
    },
    "Lari (GEL)": {
      ISOAlphacode: "GEL",
      name: "Lari",
      ISONumeric: 981,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: false,
      grapheme: "",
      template: "$1 ",
    },
    "Ghana Cedi (GHS)": {
      ISOAlphacode: "GHS",
      name: "Ghana Cedi",
      ISONumeric: 936,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: true,
      grapheme: "&#xa2;",
      template: "$1 ",
    },
    "Gibraltar Pound (GIP)": {
      ISOAlphacode: "GIP",
      name: "Gibraltar Pound",
      ISONumeric: 292,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: true,
      grapheme: "&#xa3;",
      template: "$1 ",
    },
    "Dalasi (GMD)": {
      ISOAlphacode: "GMD",
      name: "Dalasi",
      ISONumeric: 270,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: false,
      grapheme: "",
      template: "$1 ",
    },
    "Quetzal (GTQ)": {
      ISOAlphacode: "GTQ",
      name: "Quetzal",
      ISONumeric: 320,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: true,
      grapheme: "&#x51;",
      template: "$1 ",
    },
    "Guyana Dollar (GYD)": {
      ISOAlphacode: "GYD",
      name: "Guyana Dollar",
      ISONumeric: 328,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: true,
      grapheme: "&#x24;",
      template: "$1 ",
    },
    "Hong Kong Dollar (HKD)": {
      ISOAlphacode: "HKD",
      name: "Hong Kong Dollar",
      ISONumeric: 344,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: true,
      grapheme: "&#x24;",
      template: "$1 ",
    },
    "Lempira (HNL)": {
      ISOAlphacode: "HNL",
      name: "Lempira",
      ISONumeric: 340,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: true,
      grapheme: "&#x4c;",
      template: "$1 ",
    },
    "Kuna (HRK)": {
      ISOAlphacode: "HRK",
      name: "Kuna",
      ISONumeric: 191,
      fractionSize: 2,
      displayFormat: "#.###,##",
      thousandSeparator: ".",
      decimalSeparator: ",",
      hasSymbol: true,
      grapheme: "&#x6b;&#x6e;",
      template: "$1 ",
    },
    "Gourde (HTG)": {
      ISOAlphacode: "HTG",
      name: "Gourde",
      ISONumeric: 332,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: false,
      grapheme: "",
      template: "$1 ",
    },
    "Forint (HUF)": {
      ISOAlphacode: "HUF",
      name: "Forint",
      ISONumeric: 348,
      fractionSize: 2,
      displayFormat: "#.###.##",
      thousandSeparator: ".",
      decimalSeparator: ".",
      hasSymbol: true,
      grapheme: "&#x46;&#x74;",
      template: "$1 ",
    },
    "Rupiah (IDR)": {
      ISOAlphacode: "IDR",
      name: "Rupiah",
      ISONumeric: 360,
      fractionSize: 2,
      displayFormat: "#.###,##",
      thousandSeparator: ".",
      decimalSeparator: ",",
      hasSymbol: true,
      grapheme: "&#x52;&#x70;",
      template: "$1 ",
    },
    "New Israeli Shekel (ILS)": {
      ISOAlphacode: "ILS",
      name: "New Israeli Shekel",
      ISONumeric: 376,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: true,
      grapheme: "&#x20aa;",
      template: "$1 ",
    },
    "Indian Rupee (INR)": {
      ISOAlphacode: "INR",
      name: "Indian Rupee",
      ISONumeric: 356,
      fractionSize: 2,
      displayFormat: "#,##,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: true,
      grapheme: "&#x20B9;",
      template: "$1 ",
    },
    "Iraqi Dinar (IQD)": {
      ISOAlphacode: "IQD",
      name: "Iraqi Dinar",
      ISONumeric: 368,
      fractionSize: 3,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: true,
      grapheme: "&#x62F.&#x639;",
      template: "$1 ",
    },
    "Iceland Krona (ISK)": {
      ISOAlphacode: "ISK",
      name: "Iceland Krona",
      ISONumeric: 352,
      fractionSize: 0,
      displayFormat: "#.###",
      thousandSeparator: ".",
      decimalSeparator: "",
      hasSymbol: true,
      grapheme: "&#x6b;&#x72;",
      template: "$1 ",
    },
    "Jamaican Dollar (JMD)": {
      ISOAlphacode: "JMD",
      name: "Jamaican Dollar",
      ISONumeric: 388,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: true,
      grapheme: "&#x4a;&#x24;",
      template: "$1 ",
    },
    "Jordanian Dinar (JOD)": {
      ISOAlphacode: "JOD",
      name: "Jordanian Dinar",
      ISONumeric: 400,
      fractionSize: 3,
      displayFormat: "#,###.###",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: false,
      grapheme: "",
      template: "$1 ",
    },
    "Yen (JPY)": {
      ISOAlphacode: "JPY",
      name: "Yen",
      ISONumeric: 392,
      fractionSize: 0,
      displayFormat: "#,###",
      thousandSeparator: ",",
      decimalSeparator: "",
      hasSymbol: true,
      grapheme: "Â¥",
      template: "$1 ",
    },
    "Kenyan Shilling (KES)": {
      ISOAlphacode: "KES",
      name: "Kenyan Shilling",
      ISONumeric: 404,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: false,
      grapheme: "",
      template: "$1 ",
    },
    "Som (KGS)": {
      ISOAlphacode: "KGS",
      name: "Som",
      ISONumeric: 417,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: true,
      grapheme: "&#x43b;&#x432;",
      template: "$1 ",
    },
    "Riel (KHR)": {
      ISOAlphacode: "KHR",
      name: "Riel",
      ISONumeric: 116,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: true,
      grapheme: "&#x17db;",
      template: "$1 ",
    },
    "Comorian Franc (KMF)": {
      ISOAlphacode: "KMF",
      name: "Comorian Franc",
      ISONumeric: 174,
      fractionSize: 0,
      displayFormat: "#,###",
      thousandSeparator: ",",
      decimalSeparator: "",
      hasSymbol: false,
      grapheme: "",
      template: "$1 ",
    },
    "Won (KRW)": {
      ISOAlphacode: "KRW",
      name: "Won",
      ISONumeric: 410,
      fractionSize: 0,
      displayFormat: "#,###",
      thousandSeparator: ",",
      decimalSeparator: "",
      hasSymbol: true,
      grapheme: "â‚©",
      template: "$1 ",
    },
    "Kuwaiti Dinar (KWD)": {
      ISOAlphacode: "KWD",
      name: "Kuwaiti Dinar",
      ISONumeric: 414,
      fractionSize: 3,
      displayFormat: "#,###.###",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: true,
      grapheme: "&#x643;",
      template: "$1 ",
    },
    "Cayman Islands Dollar (KYD)": {
      ISOAlphacode: "KYD",
      name: "Cayman Islands Dollar",
      ISONumeric: 136,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: true,
      grapheme: "&#x24;",
      template: "$1 ",
    },
    "Tenge (KZT)": {
      ISOAlphacode: "KZT",
      name: "Tenge",
      ISONumeric: 398,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: true,
      grapheme: "&#x43b;&#x432;",
      template: "$1 ",
    },
    "Lao Kip (LAK)": {
      ISOAlphacode: "LAK",
      name: "Lao Kip",
      ISONumeric: 418,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: true,
      grapheme: "&#x20ad;",
      template: "$1 ",
    },
    "Lebanese Pound (LBP)": {
      ISOAlphacode: "LBP",
      name: "Lebanese Pound",
      ISONumeric: 422,
      fractionSize: 2,
      displayFormat: "# ###.##",
      thousandSeparator: " ",
      decimalSeparator: ".",
      hasSymbol: true,
      grapheme: "&#x644.&#x644;",
      template: "$1 ",
    },
    "Sri Lanka Rupee (LKR)": {
      ISOAlphacode: "LKR",
      name: "Sri Lanka Rupee",
      ISONumeric: 144,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: true,
      grapheme: "&#x20a8;",
      template: "$1 ",
    },
    "Liberian Dollar (LRD)": {
      ISOAlphacode: "LRD",
      name: "Liberian Dollar",
      ISONumeric: 430,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: true,
      grapheme: "&#x24;",
      template: "$1 ",
    },
    "Loti (LSL)": {
      ISOAlphacode: "LSL",
      name: "Loti",
      ISONumeric: 426,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: false,
      grapheme: "",
      template: "$1 ",
    },
    "Libyan Dinar (LYD)": {
      ISOAlphacode: "LYD",
      name: "Libyan Dinar",
      ISONumeric: 434,
      fractionSize: 3,
      displayFormat: "#,###.###",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: false,
      grapheme: "",
      template: "$1 ",
    },
    "Moroccan Dirham (MAD)": {
      ISOAlphacode: "MAD",
      name: "Moroccan Dirham",
      ISONumeric: 504,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: false,
      grapheme: "",
      template: "$1 ",
    },
    "Moldovan Leu (MDL)": {
      ISOAlphacode: "MDL",
      name: "Moldovan Leu",
      ISONumeric: 498,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: false,
      grapheme: "",
      template: "$1 ",
    },
    "Malagasy Ariary (MGA)": {
      ISOAlphacode: "MGA",
      name: "Malagasy Ariary",
      ISONumeric: 969,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: false,
      grapheme: "",
      template: "$1 ",
    },
    "Denar (MKD)": {
      ISOAlphacode: "MKD",
      name: "Denar",
      ISONumeric: 807,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: true,
      grapheme: "&#x434;&#x435;&#x43d;",
      template: "$1 ",
    },
    "Kyat (MMK)": {
      ISOAlphacode: "MMK",
      name: "Kyat",
      ISONumeric: 104,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: false,
      grapheme: "",
      template: "$1 ",
    },
    "Tugrik (MNT)": {
      ISOAlphacode: "MNT",
      name: "Tugrik",
      ISONumeric: 496,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: true,
      grapheme: "&#x20ae;",
      template: "$1 ",
    },
    "Pataca (MOP)": {
      ISOAlphacode: "MOP",
      name: "Pataca",
      ISONumeric: 446,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: false,
      grapheme: "",
      template: "$1 ",
    },
    "Ouguiya (MRO)": {
      ISOAlphacode: "MRO",
      name: "Ouguiya",
      ISONumeric: 478,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: false,
      grapheme: "",
      template: "$1 ",
    },
    "Mauritius Rupee (MUR)": {
      ISOAlphacode: "MUR",
      name: "Mauritius Rupee",
      ISONumeric: 480,
      fractionSize: 2,
      displayFormat: "#,###",
      thousandSeparator: ",",
      decimalSeparator: " ",
      hasSymbol: true,
      grapheme: "&#x20a8;",
      template: "$1 ",
    },
    "Rufiyaa (MVR)": {
      ISOAlphacode: "MVR",
      name: "Rufiyaa",
      ISONumeric: 462,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: false,
      grapheme: "",
      template: "$1 ",
    },
    "Malawi Kwacha (MWK)": {
      ISOAlphacode: "MWK",
      name: "Malawi Kwacha",
      ISONumeric: 454,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: false,
      grapheme: "",
      template: "$1 ",
    },
    "Mexican Peso (MXN)": {
      ISOAlphacode: "MXN",
      name: "Mexican Peso",
      ISONumeric: 484,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: true,
      grapheme: "&#x24;",
      template: "$1 ",
    },
    "Malaysian Ringgit (MYR)": {
      ISOAlphacode: "MYR",
      name: "Malaysian Ringgit",
      ISONumeric: 458,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: true,
      grapheme: "&#x52;&#x4d;",
      template: "$1 ",
    },
    "Mozambique Metical (MZN)": {
      ISOAlphacode: "MZN",
      name: "Mozambique Metical",
      ISONumeric: 943,
      fractionSize: 0,
      displayFormat: "#,###",
      thousandSeparator: ",",
      decimalSeparator: "",
      hasSymbol: true,
      grapheme: "&#x4d;&#x54;",
      template: "$1 ",
    },
    "Namibia Dollar (NAD)": {
      ISOAlphacode: "NAD",
      name: "Namibia Dollar",
      ISONumeric: 516,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: true,
      grapheme: "&#x24;",
      template: "$1 ",
    },
    "Naira (NGN)": {
      ISOAlphacode: "NGN",
      name: "Naira",
      ISONumeric: 566,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: true,
      grapheme: "&#x20a6;",
      template: "$1 ",
    },
    "Cordoba Oro (NIO)": {
      ISOAlphacode: "NIO",
      name: "Cordoba Oro",
      ISONumeric: 558,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: true,
      grapheme: "&#x43;&#x24;",
      template: "$1 ",
    },
    "Norwegian Krone (NOK)": {
      ISOAlphacode: "NOK",
      name: "Norwegian Krone",
      ISONumeric: 578,
      fractionSize: 2,
      displayFormat: "#.###,##",
      thousandSeparator: ".",
      decimalSeparator: ",",
      hasSymbol: true,
      grapheme: "&#x6b;&#x72;",
      template: "$1 ",
    },
    "Nepalese Rupee (NPR)": {
      ISOAlphacode: "NPR",
      name: "Nepalese Rupee",
      ISONumeric: 524,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: true,
      grapheme: "&#x20a8;",
      template: "$1 ",
    },
    "New Zealand Dollar (NZD)": {
      ISOAlphacode: "NZD",
      name: "New Zealand Dollar",
      ISONumeric: 554,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: true,
      grapheme: "&#x24;",
      template: "$1 ",
    },
    "Rial Omani (OMR)": {
      ISOAlphacode: "OMR",
      name: "Rial Omani",
      ISONumeric: 512,
      fractionSize: 3,
      displayFormat: "#,###.###",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: true,
      grapheme: "&#xfdfc;",
      template: "$1 ",
    },
    "Balboa (PAB)": {
      ISOAlphacode: "PAB",
      name: "Balboa",
      ISONumeric: 590,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: true,
      grapheme: "&#x42;&#x2f;&#x2e;",
      template: "$1 ",
    },
    "Sol (PEN)": {
      ISOAlphacode: "PEN",
      name: "Sol",
      ISONumeric: 604,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: true,
      grapheme: "&#x53;&#x2f;&#x2e;",
      template: "$1 ",
    },
    "Kina (PGK)": {
      ISOAlphacode: "PGK",
      name: "Kina",
      ISONumeric: 598,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: false,
      grapheme: "",
      template: "$1 ",
    },
    "Philippine Peso (PHP)": {
      ISOAlphacode: "PHP",
      name: "Philippine Peso",
      ISONumeric: 608,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: true,
      grapheme: "&#x20b1;",
      template: "$1 ",
    },
    "Pakistan Rupee (PKR)": {
      ISOAlphacode: "PKR",
      name: "Pakistan Rupee",
      ISONumeric: 586,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: true,
      grapheme: "&#x20a8;",
      template: "$1 ",
    },
    "Zloty (PLN)": {
      ISOAlphacode: "PLN",
      name: "Zloty",
      ISONumeric: 985,
      fractionSize: 2,
      displayFormat: "# ###,##",
      thousandSeparator: " ",
      decimalSeparator: ",",
      hasSymbol: true,
      grapheme: "&#x7a;&#x142;",
      template: "$1 ",
    },
    "Guarani (PYG)": {
      ISOAlphacode: "PYG",
      name: "Guarani",
      ISONumeric: 600,
      fractionSize: 0,
      displayFormat: "#,###",
      thousandSeparator: ",",
      decimalSeparator: "",
      hasSymbol: true,
      grapheme: "&#x47;&#x73;",
      template: "$1 ",
    },
    "Qatari Rial (QAR)": {
      ISOAlphacode: "QAR",
      name: "Qatari Rial",
      ISONumeric: 634,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: true,
      grapheme: "&#xfdfc;",
      template: "$1 ",
    },
    "Romanian Leu (RON)": {
      ISOAlphacode: "RON",
      name: "Romanian Leu",
      ISONumeric: 946,
      fractionSize: 2,
      displayFormat: "#.###,##",
      thousandSeparator: ".",
      decimalSeparator: ",",
      hasSymbol: true,
      grapheme: "&#x6c;&#x65;&#x69;",
      template: "$1 ",
    },
    "Serbian Dinar (RSD)": {
      ISOAlphacode: "RSD",
      name: "Serbian Dinar",
      ISONumeric: 941,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: true,
      grapheme: "&#x414;&#x438;&#x43d;&#x2e;",
      template: "$1 ",
    },
    "Russian Ruble (RUB)": {
      ISOAlphacode: "RUB",
      name: "Russian Ruble",
      ISONumeric: 643,
      fractionSize: 2,
      displayFormat: "#.###,##",
      thousandSeparator: ".",
      decimalSeparator: ",",
      hasSymbol: true,
      grapheme: "&#x20bd;",
      template: "$1 ",
    },
    "Rwanda Franc (RWF)": {
      ISOAlphacode: "RWF",
      name: "Rwanda Franc",
      ISONumeric: 646,
      fractionSize: 0,
      displayFormat: "#,###",
      thousandSeparator: ",",
      decimalSeparator: "",
      hasSymbol: false,
      grapheme: "",
      template: "$1 ",
    },
    "Saudi Riyal (SAR)": {
      ISOAlphacode: "SAR",
      name: "Saudi Riyal",
      ISONumeric: 682,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: true,
      grapheme: "&#xfdfc;",
      template: "$1 ",
    },
    "Solomon Islands Dollar (SBD)": {
      ISOAlphacode: "SBD",
      name: "Solomon Islands Dollar",
      ISONumeric: 90,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: true,
      grapheme: "&#x24;",
      template: "$1 ",
    },
    "Seychelles Rupee (SCR)": {
      ISOAlphacode: "SCR",
      name: "Seychelles Rupee",
      ISONumeric: 690,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: true,
      grapheme: "&#x20a8;",
      template: "$1 ",
    },
    "Sudanese Pound (SDG)": {
      ISOAlphacode: "SDG",
      name: "Sudanese Pound",
      ISONumeric: 938,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: false,
      grapheme: "",
      template: "$1 ",
    },
    "Swedish Krona (SEK)": {
      ISOAlphacode: "SEK",
      name: "Swedish Krona",
      ISONumeric: 752,
      fractionSize: 2,
      displayFormat: "# ###,##",
      thousandSeparator: " ",
      decimalSeparator: ",",
      hasSymbol: true,
      grapheme: "&#x6b;&#x72;",
      template: "$1 ",
    },
    "Singapore Dollar (SGD)": {
      ISOAlphacode: "SGD",
      name: "Singapore Dollar",
      ISONumeric: 702,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: true,
      grapheme: "&#x24;",
      template: "$1 ",
    },
    "Saint Helena Pound (SHP)": {
      ISOAlphacode: "SHP",
      name: "Saint Helena Pound",
      ISONumeric: 654,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: true,
      grapheme: "&#xa3;",
      template: "$1 ",
    },
    "Leone (SLL)": {
      ISOAlphacode: "SLL",
      name: "Leone",
      ISONumeric: 694,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: false,
      grapheme: "",
      template: "$1 ",
    },
    "Somali Shilling (SOS)": {
      ISOAlphacode: "SOS",
      name: "Somali Shilling",
      ISONumeric: 706,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: true,
      grapheme: "&#x53;",
      template: "$1 ",
    },
    "Surinam Dollar (SRD)": {
      ISOAlphacode: "SRD",
      name: "Surinam Dollar",
      ISONumeric: 968,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: true,
      grapheme: "&#x24;",
      template: "$1 ",
    },
    "Dobra (STD)": {
      ISOAlphacode: "STD",
      name: "Dobra",
      ISONumeric: 678,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: false,
      grapheme: "",
      template: "$1 ",
    },
    "El Salvador Colon (SVC)": {
      ISOAlphacode: "SVC",
      name: "El Salvador Colon",
      ISONumeric: 222,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: true,
      grapheme: "&#x24;",
      template: "$1 ",
    },
    "Lilangeni (SZL)": {
      ISOAlphacode: "SZL",
      name: "Lilangeni",
      ISONumeric: 748,
      fractionSize: 2,
      displayFormat: "#, ###.##",
      thousandSeparator: ", ",
      decimalSeparator: ".",
      hasSymbol: false,
      grapheme: "",
      template: "$1 ",
    },
    "Baht (THB)": {
      ISOAlphacode: "THB",
      name: "Baht",
      ISONumeric: 764,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: true,
      grapheme: "&#xe3f;",
      template: "$1 ",
    },
    "Somoni (TJS)": {
      ISOAlphacode: "TJS",
      name: "Somoni",
      ISONumeric: 972,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: false,
      grapheme: "",
      template: "$1 ",
    },
    "Turkmenistani New Manat (TMT)": {
      ISOAlphacode: "TMT",
      name: "Turkmenistani New Manat",
      ISONumeric: 934,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: false,
      grapheme: "",
      template: "$1 ",
    },
    "Tunisian Dinar (TND)": {
      ISOAlphacode: "TND",
      name: "Tunisian Dinar",
      ISONumeric: 788,
      fractionSize: 3,
      displayFormat: "#,###.###",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: false,
      grapheme: "",
      template: "1 $",
    },
    "Pa'anga (TOP)": {
      ISOAlphacode: "TOP",
      name: "Pa'anga",
      ISONumeric: 776,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: false,
      grapheme: "",
      template: "$1 ",
    },
    "Turkish Lira (TRY)": {
      ISOAlphacode: "TRY",
      name: "Turkish Lira",
      ISONumeric: 949,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: true,
      grapheme: "&#x20ba;",
      template: "$1 ",
    },
    "Trinidad and Tobago (TTD)": {
      ISOAlphacode: "TTD",
      name: "Trinidad and Tobago",
      ISONumeric: 780,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: true,
      grapheme: "&#x54;&#x54;&#x24;",
      template: "$1 ",
    },
    "New Taiwan Dollar (TWD)": {
      ISOAlphacode: "TWD",
      name: "New Taiwan Dollar",
      ISONumeric: 901,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: true,
      grapheme: "&#x4e;&#x54;&#x24;",
      template: "$1 ",
    },
    "Tanzanian Shilling (TZS)": {
      ISOAlphacode: "TZS",
      name: "Tanzanian Shilling",
      ISONumeric: 834,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: false,
      grapheme: "",
      template: "$1 ",
    },
    "Hryvnia (UAH)": {
      ISOAlphacode: "UAH",
      name: "Hryvnia",
      ISONumeric: 980,
      fractionSize: 2,
      displayFormat: "# ###,##",
      thousandSeparator: " ",
      decimalSeparator: ",",
      hasSymbol: true,
      grapheme: "&#x20b4;",
      template: "$1 ",
    },
    "Uganda Shilling (UGX)": {
      ISOAlphacode: "UGX",
      name: "Uganda Shilling",
      ISONumeric: 800,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: false,
      grapheme: "",
      template: "$1 ",
    },
    "US Dollar (USD)": {
      ISOAlphacode: "USD",
      name: "US Dollar",
      ISONumeric: 840,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: true,
      grapheme: "$",
      template: "$1 ",
    },
    "Peso Uruguayo (UYU)": {
      ISOAlphacode: "UYU",
      name: "Peso Uruguayo",
      ISONumeric: 858,
      fractionSize: 2,
      displayFormat: "#.###,##",
      thousandSeparator: ".",
      decimalSeparator: ",",
      hasSymbol: true,
      grapheme: "&#x24;&#x55;",
      template: "$1 ",
    },
    "Uzbekistan Sum (UZS)": {
      ISOAlphacode: "UZS",
      name: "Uzbekistan Sum",
      ISONumeric: 860,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: true,
      grapheme: "&#x43b;&#x432;",
      template: "$1 ",
    },
    "Bolivar (VEF)": {
      ISOAlphacode: "VEF",
      name: "Bolivar",
      ISONumeric: 937,
      fractionSize: 2,
      displayFormat: "#.###,##",
      thousandSeparator: ".",
      decimalSeparator: ",",
      hasSymbol: true,
      grapheme: "&#x42;&#x73;",
      template: "$1 ",
    },
    "Dong (VND)": {
      ISOAlphacode: "VND",
      name: "Dong",
      ISONumeric: 704,
      fractionSize: 0,
      displayFormat: "#.###",
      thousandSeparator: ".",
      decimalSeparator: "",
      hasSymbol: true,
      grapheme: "&#x20ab;",
      template: "$1 ",
    },
    "Vatu (VUV)": {
      ISOAlphacode: "VUV",
      name: "Vatu",
      ISONumeric: 548,
      fractionSize: 0,
      displayFormat: "#,###",
      thousandSeparator: ",",
      decimalSeparator: "",
      hasSymbol: false,
      grapheme: "",
      template: "$1 ",
    },
    "Tala (WST)": {
      ISOAlphacode: "WST",
      name: "Tala",
      ISONumeric: 882,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: false,
      grapheme: "",
      template: "$1 ",
    },
    "CFA Franc BEAC (XAF)": {
      ISOAlphacode: "XAF",
      name: "CFA Franc BEAC",
      ISONumeric: 950,
      fractionSize: 0,
      displayFormat: "#,###",
      thousandSeparator: ",",
      decimalSeparator: "",
      hasSymbol: false,
      grapheme: "",
      template: "$1 ",
    },
    "East Caribbean Dollar (XCD)": {
      ISOAlphacode: "XCD",
      name: "East Caribbean Dollar",
      ISONumeric: 951,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: true,
      grapheme: "&#x24;",
      template: "$1 ",
    },
    "CFP Franc (XPF)": {
      ISOAlphacode: "XPF",
      name: "CFP Franc",
      ISONumeric: 953,
      fractionSize: 0,
      displayFormat: "#,###",
      thousandSeparator: ",",
      decimalSeparator: "",
      hasSymbol: false,
      grapheme: "",
      template: "$1 ",
    },
    "Yemeni Rial (YER)": {
      ISOAlphacode: "YER",
      name: "Yemeni Rial",
      ISONumeric: 886,
      fractionSize: 2,
      displayFormat: "#,###.##",
      thousandSeparator: ",",
      decimalSeparator: ".",
      hasSymbol: true,
      grapheme: "&#xfdfc;",
      template: "$1 ",
    },
    "Rand (ZAR)": {
      ISOAlphacode: "ZAR",
      name: "Rand",
      ISONumeric: 710,
      fractionSize: 2,
      displayFormat: "# ###.##",
      thousandSeparator: " ",
      decimalSeparator: ".",
      hasSymbol: true,
      grapheme: "&#x52;",
      template: "$1 ",
    },
  },

  getByCode: function (code) {
    if (!code) {
      return;
    }
    var currency = this.currencies[code];
    if (!currency) {
      currency = null;
    }
    return currency;
  },
  getCurrencies: function () {
    return this.currencies;
  },
};

var formatCurrencyDisplay = function (amount, currency, currencyCode) {
  if (!currencyCode || Number(amount) != amount) {
    return;
  }

  if (currency === null || currency === undefined) {
    return "<span>" + amount + "</span>";
  }

  var formattedCurrency,
    formatedAmount = Math.abs(amount),
    signAmount = amount < 0 ? "-" : "";

  var currentFractionSize = 0;
  formatedAmount = formatedAmount.toFixed(currentFractionSize);
  if (currencyCode === "Indian Rupee (INR)") {
    var leftPart = "";
    var rightPart = "";
    var result = formatedAmount.toString().split(".");
    if (result[0] !== undefined) {
      var leftPart = result[0];
    }
    if (result[1] !== undefined) {
      var rightPart = result[1];
    }
    var leftLastThree = leftPart.substring(leftPart.length - 3);
    var leftOtherNumbers = leftPart.substring(0, leftPart.length - 3);
    if (leftOtherNumbers != "")
      leftLastThree = currency.thousandSeparator + leftLastThree;
    var leftFormatedAmount =
      leftOtherNumbers.replace(/\B(?=(\d{2})+(?!\d))/g, ",") + leftLastThree;
    var rightLastThree = rightPart.substring(rightPart.length - 3);
    var rightOtherNumbers = rightPart.substring(0, rightPart.length - 3);
    if (rightOtherNumbers != "")
      rightLastThree = currency.thousandSeparator + rightLastThree;
    var rightFormatedAmount =
      rightOtherNumbers.replace(/\B(?=(\d{2})+(?!\d))/g, ",") + rightLastThree;
    var formatedAmount =
      leftFormatedAmount + currency.decimalSeparator + rightFormatedAmount;
  } else {
    formatedAmount = formatedAmount.split(".").join(currency.decimalSeparator);
    formatedAmount = formatedAmount.replace(
      /(\d)(?=(\d{3})+(?!\d))/g,
      "$1" + currency.thousandSeparator
    );
  }
  if (!!currency && Boolean(currency.hasSymbol) && !!currency.template) {
    formattedCurrency = currency.template.replace(
      "1",
      signAmount + formatedAmount
    );
    formattedCurrency = formattedCurrency.replace(
      "$",
      "<span>" + currency.grapheme + "</span>"
    );
  } else {
    formattedCurrency = signAmount + formatedAmount;
  }
  return "<span>" + formattedCurrency + "</span>";
};
